server:
  port: 8080
  servlet:
    context-path: /marketplace

spring:
  application:
    name: marketplace
  config:
    import:
      "optional:classpath:application-secret.properties"
  datasource:
    url: jdbc:mysql://localhost:3306/marketplace
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB

com:
  marketplace:
    cloudinary:
      cloud-name: ${CLOUDINARY_CLOUD_NAME}
      api-key: ${CLOUDINARY_API_KEY}
      api-secret: ${CLOUDINARY_API_SECRET}

jwt:
  signerKey: "a4aec8aa399e085aa2c40ae8106d7bb6c55c825a6149916bfcc9920e441d05c2"
  valid-duration: 3600
  refreshable-duration: 36000
